# Generated by Django 5.0.1 on 2024-01-30 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everyco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='slug',
        ),
    ]
